### ISSUE TITLE
Facing some errors running on Python 3.11.1 and Windows 10 Pro

### ISSUE THREAD

**Issue by adrianopizzini** [aliparsai/LittleDarwin#17]
I am facing some errors running LD on open source projects.

**1. Cucumber-jvm-7.11.1**
**1.1. initial build is ok (mvn clean install)**
**1.2. Error running mutation phase**
python -m littledarwin -m -v -p .\cucumber-core\src\main -c mvn,install -t .\ --test-path=.\cucumber-core\ --test-command=mvn,test

(76/182) Source file:  C:\cucumber-jvm-7.11.1\cucumber-core\src\main\java\io\cucumber\core\plugin\Banner.java
ANTLR runtime and generated code versions disagree: 4.11.1!=4.10.1
ANTLR runtime and generated code versions disagree: 4.11.1!=4.10.1
line 61:51 token recognition error at: ''â”'
line 61:54 token recognition error at: '€'
line 61:55 token recognition error at: '', '
line 78:51 token recognition error at: ''â”'
line 78:54 token recognition error at: '€'
line 78:55 token recognition error at: '', '
--> Mutations found:  3
----> ArithmeticOperatorReplacementBinary : 3
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\littledarwin\__main__.py", line 16, in <module>
    sys.exit(entryPoint())
             ^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\littledarwin\__main__.py", line 12, in entryPoint
    LittleDarwin.main()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\littledarwin\LittleDarwin.py", line 92, in main
    mutationPhase(options, filterType, filterList, higherOrder)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\littledarwin\LittleDarwin.py", line 203, in mutationPhase
    targetList.append(javaIO.generateNewFile(srcFile, mutatedFile, javaMutate.mutantsPerLine,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\littledarwin\JavaIO.py", line 177, in generateNewFile
    densityFileHandle.write(densityReport)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 10599: character maps to <undefined>

**2. graphhopper-6.2**
**2.1. initial build ok (mvn clean install)**
**2.2. Mutation phase ok**
python -m littledarwin -m -v -p .\core\src\main -c mvn,clean,install -t .\ --test-path=.\core\src\test --test-command=mvn,test

Total mutations found:  7020
--> ShiftOperatorReplacement: 140
--> ArithmeticOperatorReplacementShortcut: 358
--> ConditionalOperatorDeletion: 656
--> ArithmeticOperatorReplacementBinary: 2123
--> RelationalOperatorReplacement: 2290
--> AssignmentOperatorReplacementShortcut: 218
--> ArithmeticOperatorReplacementUnary: 231
--> ConditionalOperatorReplacement: 862
--> LogicalOperatorReplacement: 142

**2.3. Build phase doesn't run**

!!! CAUTION !!!
Code can be changed accidentally. Create a backup first.

Initial build... C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\subprocess.py:1008: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdin = io.open(p2cwrite, 'wb', bufsize)
C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\subprocess.py:1014: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
ÊXITO: o processo com PID 8444 (processo filho de PID 8820) foi finalizado.
ÊXITO: o processo com PID 8936 (processo filho de PID 8820) foi finalizado.
ÊXITO: o processo com PID 8820 (processo filho de PID 816) foi finalizado.
ÊXITO: o processo com PID 816 (processo filho de PID 6212) foi finalizado.
ÊXITO: o processo com PID 6212 (processo filho de PID 8232) foi finalizado.
failed.

Initial build failed. Try building the system manually first to make sure it can be built. Take a look at C:\graphhopper-6.2\LittleDarwinResults\initialbuild.txt to find out why this happened.

**2.3.1. There is no error reported in "initialbuild.txt"**
com.graphhopper.routing.RandomizedRoutingTest\r\n[INFO] Running com.graphhopper.routing.RoundTripRoutingTest\r\n[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in com.graphhopper.routing.RoundTripRoutingTest\r\n[INFO] Running com.graphhopper.routing.RoutingAlgorithmTest\r\n[INFO] Tests run: 377, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.281 s - in com.graphhopper.routing.RoutingAlgorithmTest\r\n[INFO] Running com.graphhopper.routing.RoutingAlgorithmWithOSMTest\r\n2023-11-16 19:47:48.748 [car] ERROR c.g.routing.lm.LandmarkStorage - method findLandmarks for 0.001,0.0 (3) resulted in too few visited nodes: 1 vs expected minimum 3, see #2256\r\n"

**Comment by aliparsai** [comment]
For 1.2 it looks like a unicode error, can you attach the source files to this ticket so that I can replicate it?

For 2.3.1 there is an error there: 
[INFO] Running com.graphhopper.routing.RoutingAlgorithmWithOSMTest
**2023-11-16 19:47:48.748 [car] ERROR c.g.routing.lm.LandmarkStorage - method findLandmarks for 0.001,0.0 (3) resulted in too few visited nodes: 1 vs expected minimum 3, see #2256**
LittleDarwin uses the exit code of the build system to detect an error state. Since there's an error during build. it is returning a non-zero exit code, and that fails the initial build. For this to go away, you need to make sure you can run the build system on its own without any error codes occuring.

**Comment by aliparsai** [comment]
> About 2.3.1, I was building every project before running LD. Some projects had errors when running the tests, but the project was successfully built.

Mutation testing requires a green test suite, i.e. all tests pass. Otherwise, it is not possible to distinguish a pre-existing test failure and a failure caused by a mutant. That's why we do an initial build, to make sure everything is good to go before starting the mutation testing process. If there's a test failure in the intial build, that counts as a failure. Make sure the build (including the test phase) completes without any errors before performing mutation testing.
