### ISSUE TITLE
Add Jupyter notebook examples

### ISSUE THREAD

**Issue by jacksonpradolima** [aliparsai/LittleDarwin#5]
Hello,
It's nice to see more contributions for Mutation Testing, and it's a necessity to have a framework actually.

It would be nice to have Jupyter notebooks in a main "examples" folder showing the different options to use with LittleDarwin. It could contain the same exact code as the examples in the .py files, but with comments to provide a better understanding. Even, provides a "case study".

**Comment by aliparsai** [comment]
no further usecase.
