### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by nimashiri** [aliparsai/LittleDarwin#7]
The line number 290 of the `LittleDarwin.py` module raises a TypeError message. I think it is better to change :

`sys.stderr.write(e.message)`
to:
`sys.stderr.write(e.args[0])`

Thanks.

**Comment by aliparsai** [comment]
Can you let me know the context in which you received this error? What kind of Java source code was not parsable?

**Comment by nimashiri** [comment]
Hi dear Ali,

The error raised on the file attached to this email. I am using your
library on the ant-1.4 project.
I changed *sys.stderr.write(e.message)* to *sys.stderr.write(e.args[0]) *and
now your library works smoothly.

BTW, thanks for your awesome library.

Regards,

Nima.

**Comment by aliparsai** [comment]
Indeed the TypeError happens because of the recent move to Python3, and on the newest snapshot this must be fixed now. But the parse error seems to be because Java 3 or earlier did not have enum as a keyword. So that's why some old files can't be parsed. Thanks for reporting this. ;)

**Comment by nimashiri** [comment]
Thanks for the explanations.

Would you please let me know which mutation operators are used in your
library?
When I use littledarwin for mutation generation, for each class, multiple
mutated counterparts are generated (ordered by the number e.g. 1 to 10) in
conjunction with the original source code. However, I don't know which
mutation operator is performed for that class.

It would be great to run the program per operator on all files.
First run, ROR on all files
Second run, AOR on all files,
.
.
nth run, LOI on all files.


Thanks,

Nima.

**Comment by aliparsai** [comment]
This is not a good place to have this conversation. Maybe create a feature request, or even better, implement it yourself and create a pull request. The place you want to look in source code is JavaMutate.py and in particular applyMutators method.
